version: '3.1'
services:
  db:
    image: mysql
    container_name: mysql
    environment:
      DOCKER_HOST: //localhost
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3307"
    volumes:
      - devdojo_data:/var/lib/mysql

volumes:
  devdojo_data: